#!/bin/bash
# github.com/YetAnotherMechanicusEnjoyer

set -e

printf '\n\e[94m\e[1m'
figlet -f slant "Discord Update"
printf "\e[90mby \e[92m\e[4mYetAnotherMechanicusEnjoyer\n\n\e[0m\e[1m"

echo -e "\e[95m[Checking] => Dependencies :"

printf "\e[96m  [Dependency] => Wget..."
if command -v wget >/dev/null 2>&1; then
  printf "\n\e[92m  [✓] SUCCESS => Already installed.\n"
else
  echo -e "\e[91m  [✕] ERROR => 'wget' is missing. Can't install dependencies."
  exit 1
fi

printf "\e[96m  [Dependency] => Gum..."
gum_package="./dependencies/gum"

if command -v gum >/dev/null 2>&1; then
  printf "\n\e[92m  [✓] SUCCESS => Already installed.\n"
else
  printf "\n\e[95m   [Installling] => Gum package\n"
  if [ -f "$gum_package" ]; then
    if ! sudo sh $gum_package; then
      cd - >/dev/null
      rm -rf "$TMPDIR"
      exit 1
    fi
    printf "\e[92m   [✓] SUCCESS => Gum package installed.\n"
  else
    echo -e "\e[91m   [✕] ERROR => $gum_package is missing. Can't install dependency."
    exit 1
  fi
fi
printf "\e[92m[✓] SUCCESS => All dependencies are installed.\n\n"

action=$(gum choose "install/update" "uninstall" "quit")
echo -e "\e[1m\e[95m> $action\n"

if [[ $action == "install/update" ]]; then
  format=$(gum choose "tar.gz" "deb")
  echo -e "\e[1m\e[95m> $format\n"

  if [[ $format == "tar.gz" ]]; then
    TMPDIR=$(mktemp -d)
    cd "$TMPDIR"

    printf '\e[1m\e[95m[Downloading] => Discord latest version :\n\e[96m [Platform] => Linux\n [Format] => tar.gz\n'

    downloadURL="https://discord.com/api/download?platform=linux&format=tar.gz"
    updatePath="discord.tar.gz"

    wget -t 5 -q -O "$updatePath" --show-progress "$downloadURL"

    echo -e "\e[92m[✓] SUCCESS => Discord downloaded.\e[0m"
    if [ -f "$updatePath" ]; then
      installPath="/opt/discord"

      if [ -d "$installPath" ]; then
        echo -e "\e[1m\e[91m[Deleting] => Old $installPath\e[0m"
        if ! sudo rm -rf "$installPath"; then
          cd - >/dev/null
          rm -rf "$TMPDIR"
          exit 1
        fi
      fi

      if ! sudo mkdir -p "$installPath"; then
        cd - >/dev/null
        rm -rf "$TMPDIR"
        exit 1
      fi
      echo -e "\e[1m\e[95m[Extracting] $updatePath => $installPath\e[0m"
      if ! sudo tar -xf "$updatePath" -C "$installPath" --strip-components=1; then
        cd - >/dev/null
        rm -rf "$TMPDIR"
        exit 1
      fi

      echo -e "\e[1m\e[92m[✓] SUCCESS => $updatePath extracted into $installPath."
    else
      echo -e "\e[1m\e[91m[✕] ERROR => Couldn't download Discord from api.\e[0m"
      cd - >/dev/null
      rm -rf "$TMPDIR"
      gum spin --spinner minidot --title "Aborting..." -- sleep 2
      exit 1
    fi
    cd - >/dev/null
    rm -rf "$TMPDIR"
    gum spin --spinner minidot --title "Discord is now updated !" -- sleep 3

  elif [[ $format == "deb" ]]; then
    TMPDIR=$(mktemp -d)
    cd "$TMPDIR"

    printf '\e[95m[Downloading] => Discord latest version :\n \e[96m[Platform] => Linux\n [Format] => deb\n'

    downloadURL="https://discord.com/api/download?platform=linux&format=deb"
    updatePath="discord.deb"

    wget -t 5 -q -O "$updatePath" --show-progress "$downloadURL"

    echo -e "\e[92m[✓] SUCCESS => Discord downloaded."
    if [ -f "$updatePath" ]; then
      echo -e "\e[95m[Installing] $updatePath package & its dependencies.\e[0m"

      if command -v apt >/dev/null 2>&1; then
        printf ""
      else
        echo -e "\e[1m\e[91m[✕] ERROR => 'apt' is not installed. Can't install with '.deb'.\e[0m"
        cd - >/dev/null
        rm -rf "$TMPDIR"
        gum spin --spinner minidot --title "Aborting..." -- sleep 2
        exit 1
      fi

      if ! sudo apt install "$updatePath"; then
        cd - >/dev/null
        rm -rf "$TMPDIR"
        exit 1
      fi
      echo -e "\e[1m\e[92m[✓] SUCCESS => Disocrd package installed.\e[0m"
    else
      echo -e "\e[1m\e[91m[✕] ERROR => Couldn't download Discord from api.\e[0m"
      cd - >/dev/null
      rm -rf "$TMPDIR"
      gum spin --spinner minidot --title "Aborting..." -- sleep 2
      exit 1
    fi
    cd - >/dev/null
    rm -rf "$TMPDIR"
    gum spin --spinner jump --title "Discord is now updated !" -- sleep 2
  fi
elif [[ $format == "uninstall" ]]; then
  gum confirm && (echo -e "\e[91m[Deleting] => /opt/discord\e[0m" && sudo rm -rf "/opt/discord") || gum spin --spinner dot --title "Aborting..." -- sleep 2
  gum spin --spinner jump --title "Discord is now uninstalled !" -- sleep 2
  exit
else
  gum spin --spinner minidot --title "Aborted." -- sleep 1
  exit
fi
