#!/bin/bash
# github.com/YetAnotherMechanicusEnjoyer

set -e

printf '\n''\e[94m\e[1m    ____  _                          __   __  __          __      __     \n''   / __ \(_)_____________  _________/ /  / / / /___  ____/ /___ _/ /____ \n''  / / / / / ___/ ___/ __ \/ ___/ __  /  / / / / __ \/ __  / __ `/ __/ _ \ \n'' / /_/ / (__  ) /__/ /_/ / /  / /_/ /  / /_/ / /_/ / /_/ / /_/ / /_/  __/\n''/_____/_/____/\___/\____/_/   \__,_/   \____/ .___/\__,_/\__,_/\__/\___/ \n''                                           /_/                           \n'
printf "\e[90mby \e[92m\e[4mYetAnotherMechanicusEnjoyer\n\n\e[0m\e[1m"

echo -e "\e[95m[Checking] => Dependencies :"

printf "\e[96m  [Dependency] => Wget..."
if command -v wget >/dev/null 2>&1; then
  printf "\n\e[92m  [✓] SUCCESS => Already installed.\n"
else
  echo -e "\e[91m  [✕] ERROR => 'wget' is missing. Can't install dependencies."
  exit 1
fi

printf "\e[96m  [Dependency] => Gum..."
gum_package="./dependencies/gum"

if command -v gum >/dev/null 2>&1; then
  printf "\n\e[92m  [✓] SUCCESS => Already installed.\n"
else
  printf "\n\e[95m   [Installling] => Gum package\n"
  if [ -f "$gum_package" ]; then
    sudo sh $gum_package
    printf "\e[92m   [✓] SUCCESS => Gum package installed.\n"
  else
    echo -e "\e[91m   [✕] ERROR => $gum_package is missing. Can't install dependency."
    exit 1
  fi
fi
printf "\e[92m[✓] SUCCESS => All dependencies are installed.\n\n"

format=$(gum choose "tar.gz" "deb" "uninstall" "quit")

echo -e "\e[1m\e[95m> $format\n"
if [[ $format == "tar.gz" ]]; then
  TMPDIR=$(mktemp -d)
  cd "$TMPDIR"

  printf '\e[95m[Downloading] => Discord latest version :\n\e[96m [Platform] => Linux\n [Format] => tar.gz\n'

  downloadURL="https://discord.com/api/download?platform=linux&format=tar.gz"
  updatePath="discord.tar.gz"

  wget -t 5 -q -O "$updatePath" --show-progress "$downloadURL"

  echo -e "\e[92m[✓] SUCCESS => Discord downloaded."
  if [ -f "$updatePath" ]; then
    installPath="/opt/discord"

    if [ -d "$installPath" ]; then
      echo -e "\e[91m[Deleting] => Old $installPath"
      sudo rm -rf "$installPath"
    fi

    sudo mkdir -p "$installPath"
    echo -e "\e[95m[Extracting] $updatePath => $installPath"
    sudo tar -xf "$updatePath" -C "$installPath" --strip-components=1

    echo -e "\e[92m[✓] SUCCESS => $updatePath extracted into $installPath."
  else
    echo -e "\e[1m\e[91m[✕] ERROR => Couldn't download Discord from api."
    cd -
    rm -rf "$TMPDIR"
    gum spin --spinner minidot --title "Aborting..." -- sleep 2
    exit 1
  fi
  cd - >/dev/null
  rm -rf "$TMPDIR"
  gum spin --spinner minidot --title "Discord is now updated !" -- sleep 3
elif [[ $format == "deb" ]]; then
  printf '\e[95m[Downloading] => Discord latest version :\n \e[96m[Platform] => Linux\n [Format] => deb\n'

  downloadURL="https://discord.com/api/download?platform=linux&format=deb"
  updatePath="discord.deb"

  wget -t 5 -q -O "$updatePath" --show-progress "$downloadURL"

  echo -e "\e[92m[✓] SUCCESS => Discord downloaded."
  if [ -f "$updatePath" ]; then
    echo -e "\e[95m[Installing] $updatePath package & its dependencies."

    if command -v apt >/dev/null 2>&1; then
      printf ""
    else
      echo -e "\e[1m\e[91m[✕] ERROR => 'apt' is not installed. Can't install with '.deb'."
      cd - >/dev/null
      rm -rf "$TMPDIR"
      gum spin --spinner minidot --title "Aborting..." -- sleep 2
      exit 1
    fi

    sudo apt install "$updatePath"
    echo -e "\e[92m[✓] SUCCESS => Disocrd package installed."
  else
    echo -e "\e[1m\e[91m[✕] ERROR => Couldn't download Discord from api."
    cd - >/dev/null
    rm -rf "$TMPDIR"
    gum spin --spinner minidot --title "Aborting..." -- sleep 2
    exit 1
  fi
  cd - >/dev/null
  rm -rf "$TMPDIR"
  gum spin --spinner jump --title "Discord is now updated !" -- sleep 2
elif [[ $format == "uninstall" ]]; then
  gum confirm && (echo -e "\e[91m[Deleting] => /opt/discord" && sudo rm -rf "/opt/discord") || gum spin --spinner dot --title "Aborting..." -- sleep 2
  gum spin --spinner jump --title "Discord is now uninstalled !" -- sleep 2
  exit
else
  gum spin --spinner minidot --title "Aborted." -- sleep 2
  exit
fi
