#!/bin/bash

set -e

if [ "$EUID" -ne 0 ]; then
  echo "   [✕] ERROR => Script must be run as root."
  exit 1
fi

ARCH=$(uname -m)
case "$ARCH" in
x86_64) ARCH="x86_64" ;;
aarch64 | arm64) ARCH="arm64" ;;
*)
  exit 1
  ;;
esac

TMPDIR=$(mktemp -d)
cd "$TMPDIR"

FILE="gum_0.16.0_Linux_${ARCH}"
GUM_URL="https://github.com/charmbracelet/gum/releases/download/v0.16.0/${FILE}.tar.gz"
INSTALL_PATH="gum.tar.gz"
echo "   [Downloading] => Gum from github.com/charmbracelet/gum"
wget -t 5 -q -O "$INSTALL_PATH" --show-progress "$GUM_URL"
echo "   [✓] SUCCESS"

echo "   [Extracting] => $INSTALL_PATH"
tar -xzf "$INSTALL_PATH"
mv "${FILE}/gum" "/usr/local/bin/"
chmod +x "/usr/local/bin/gum"
echo "   [✓] SUCCESS"

cd -
rm -rf "$TMPDIR"
